[package]
name = "circuits"
version = "0.1.0"
edition = "2021"

[dependencies]
boolify = { git = "https://github.com/voltrevo/boolify", rev = "e9707c0" }
bristol-circuit = { git = "https://github.com/voltrevo/bristol-circuit", rev = "2a8b001" }
